name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Cache Node modules and Playwright browsers
      - name: Cache Node modules and Playwright
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: setup-${{ hashFiles('**/package-lock.json') }}

      # Install Node dependencies
      - name: Install Node dependencies
        run: npm ci

      # Install Playwright browsers with system dependencies
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

  test:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.2-focal
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: setup-${{ hashFiles('**/package-lock.json') }}
          
      # Run Playwright tests
      - name: Run Playwright tests
        run: |
          set -o pipefail
          npx playwright test --workers=4 --reporter=list,html --project=${{ matrix.browser }}
          
      # Upload HTML report
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 30